# Generated by Django 5.0.1 on 2024-02-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0002_alter_bike_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='description1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='description2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='description3',
            field=models.TextField(blank=True),
        ),
    ]
