# Generated by Django 5.0.1 on 2024-02-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0003_alter_bike_description1_alter_bike_description2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
