# Generated by Django 5.0.1 on 2024-02-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0004_alter_bike_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
