# Generated by Django 5.0.1 on 2024-02-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0006_alter_bike_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='accesories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='cc_engine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='mile_service',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='ps_peak_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='torque',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
