# Generated by Django 5.0.1 on 2024-02-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0007_bike_accesories_bike_cc_engine_bike_mile_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='cylinders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='kg_lighter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='kg_wet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='rpm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
