# Generated by Django 5.0.1 on 2024-02-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0008_bike_cylinders_bike_kg_lighter_bike_kg_wet_bike_rpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='nm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
