# Generated by Django 4.2 on 2024-02-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0011_remove_bike_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='engine',
            field=models.TextField(blank=True),
        ),
    ]
