# Generated by Django 4.2 on 2024-02-14 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0012_bike_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(upload_to='')),
                ('carousel_image2', models.ImageField(upload_to='')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trumphapp.bike')),
            ],
        ),
    ]
