# Generated by Django 4.2 on 2024-02-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0013_bikedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikedetails',
            old_name='bike',
            new_name='name',
        ),
    ]
