# Generated by Django 4.2 on 2024-02-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0014_rename_bike_bikedetails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikedetails',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
