# Generated by Django 4.2 on 2024-02-14 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0015_alter_bikedetails_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikedetails',
            name='bike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trumphapp.bike'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
