# Generated by Django 4.2 on 2024-02-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0018_alter_bikedetails_vedio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikedetails',
            name='vedio_url1',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='vedio_url2',
            field=models.URLField(blank=True, max_length=600),
        ),
    ]
