# Generated by Django 4.2 on 2024-02-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0020_bikedetails_bore_bikedetails_co2_figures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikedetails',
            name='Gearbox',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='Stroke',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
