# Generated by Django 4.2 on 2024-02-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0021_bikedetails_gearbox_bikedetails_stroke'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikedetails',
            name='Brakes',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='Compliance',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='Connectivity',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='Engine',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='Instruments',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='Lighting',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='Power_Torque',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='Riding_Modes',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='Shift_Assist',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='Suspension',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='Traction_Control',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
