# Generated by Django 4.2 on 2024-02-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0022_bikedetails_brakes_bikedetails_compliance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikedetails',
            name='c_image1',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='c_image2',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='c_para1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='c_para2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='c_tittle1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='c_tittle2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='mc_image1',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='mc_image2',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='mc_image3',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='mc_image4',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='mc_image5',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='mc_para1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='mc_para2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='mc_para3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='mc_para4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='mc_para5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='mc_tittle1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='mc_tittle2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='mc_tittle3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='mc_tittle4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='mc_tittle5',
            field=models.TextField(blank=True),
        ),
    ]
