# Generated by Django 4.2 on 2024-02-15 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0023_bikedetails_c_image1_bikedetails_c_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikedetails',
            name='reason_image',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_para1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_para10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_para11',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_para12',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_para2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_para3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_para4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_para5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_para6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_para7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_para8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_para9',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_tittle1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_tittle2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_tittle3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_tittle4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_tittle5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_tittle6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_tittle7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_tittle8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_video',
            field=models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
