# Generated by Django 4.2 on 2024-02-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0024_bikedetails_reason_image_bikedetails_reason_para1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikedetails',
            name='reason_image1',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_image2',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='reason_image3',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
    ]
