# Generated by Django 4.2 on 2024-02-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0026_bikedetails_access_li1_bikedetails_access_li10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikedetails',
            name='access_image1',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='access_image2',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='access_image3',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='access_image4',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='access_image5',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
        migrations.AddField(
            model_name='bikedetails',
            name='access_image6',
            field=models.ImageField(null=True, upload_to='bike_images/'),
        ),
    ]
