# Generated by Django 4.2 on 2024-02-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0027_bikedetails_access_image1_bikedetails_access_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikedetails',
            name='access_para7',
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='access_image1',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='access_image2',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='access_image3',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='access_image4',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='access_image5',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='access_image6',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='c_image1',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='c_image2',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='mc_image1',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='mc_image2',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='mc_image3',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='mc_image4',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='mc_image5',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='reason_image',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='reason_image1',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='reason_image2',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='reason_image3',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
    ]
