# Generated by Django 4.2 on 2024-02-15 16:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trumphapp', '0028_remove_bikedetails_access_para7_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikedetails',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trumphapp.bike'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='carousel_image',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='carousel_image2',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='carousel_image3',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikedetails',
            name='reason_video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
